In [62]:
import numpy as np
import math
import matplotlib.pyplot as plt
import sklearn

In [3]:
q2_data = np.load('./hw2/q2_data.npz')
X_train = q2_data['q2x_train']
Y_train = q2_data['q2y_train']
X_test = q2_data['q2x_test']
Y_test = q2_data['q2y_test']

print(X_train.shape)
print(Y_train.shape)
print(X_test.shape)
print(Y_test.shape)

(100, 4)
(100, 1)
(50, 4)
(50, 1)


In [42]:
alpha = 0.0005
K = 3
N_train = X_train.shape[0]
PHI_train = PHI = np.concatenate((np.ones((N_train, 1)), X_train), axis=1)
M_train = PHI_train.shape[1]
N_test = X_test.shape[0]
PHI_test = PHI = np.concatenate((np.ones((N_test, 1)), X_test), axis=1)
M_test = PHI_test.shape[1]

In [57]:
def get_P(W,PHI,inx,order):
    K = W.shape[1]
    M = W.shape[0]
    temp = np.dot(PHI[order,:], W)
    #print(temp)
    sum = 0
    for j in range(K-1):
        sum = sum + math.exp(temp[j])
    if inx == K:
        sum = 1/(1 + sum)
    else:
        sum = math.exp(temp[inx-1])/(1 + sum)
    return sum

np.random.seed(0)
W = np.random.random((M_train,K))
print(W)
#W = np.ones((5,3))
for i in range(1,4):
    P = get_P(W, PHI_train, i, 30)
    print(P)

[[0.5488135  0.71518937 0.60276338]
 [0.54488318 0.4236548  0.64589411]
 [0.43758721 0.891773   0.96366276]
 [0.38344152 0.79172504 0.52889492]
 [0.56804456 0.92559664 0.07103606]]
0.1237666373150701
0.8759021739200743
0.000331188764855573


In [85]:
def gradient_ascent(PHI, Y, W):
    WWW = np.zeros(W.shape)
    K = W.shape[1]
    M = W.shape[0]
    N = PHI.shape[0]
    for inx in range(1, K+1):
        sum = 0
        for j in range(N):
            sum = sum + PHI[[j],:] * ((Y[j,0] == inx) - get_P(W, PHI, inx, j))
        print(sum)
        WWW[:, [inx-1]] = sum.T
    return WWW

np.random.seed(0)
W = np.random.random((M_train,K))
WWW = gradient_ascent(PHI_train, Y_train, W)
print(WWW)

[[ 25.52693992 124.79080401  88.03043182  30.55627949   3.59463405]]
[[ -56.50267902 -328.37106795 -178.95450299 -203.81535719  -66.28684672]]
[[ 30.9757391  203.58026393  90.92407116 173.2590777   62.69221267]]
[[  25.52693992  -56.50267902   30.9757391 ]
 [ 124.79080401 -328.37106795  203.58026393]
 [  88.03043182 -178.95450299   90.92407116]
 [  30.55627949 -203.81535719  173.2590777 ]
 [   3.59463405  -66.28684672   62.69221267]]


In [92]:
iter = 500
np.random.seed(0)
W = np.random.random((M_train,K))
for i in range(iter):
    W = W + alpha*gradient_ascent(PHI_train, Y_train, W)
print(W)

[[ 25.52693992 124.79080401  88.03043182  30.55627949   3.59463405]]
[[ -56.50267902 -328.37106795 -178.95450299 -203.81535719  -66.28684672]]
[[ 30.9757391  203.58026393  90.92407116 173.2590777   62.69221267]]
[[ -4.31164293 -45.896822    -2.13985275 -73.39863017 -28.03586239]]
[[ -26.63527162 -157.53788709  -88.69387047  -99.80417606  -34.64400551]]
[[ 30.94691455 203.43470909  90.83372322 173.20280622  62.6798679 ]]
[[ -16.36130951 -116.79731828  -38.36676059 -120.02090151  -42.79959998]]
[[-14.55926367 -86.50310514 -52.38496466 -53.12693419 -19.86755031]]
[[ 30.92057318 203.30042342  90.75172525 173.1478357   62.66715029]]
[[-11.45068932 -86.98289683 -23.95091531 -98.59869146 -35.78802996]]
[[ -19.4269988  -116.09853902  -66.66721687  -74.45973123  -26.85849878]]
[[ 30.87768812 203.08143585  90.61813218 173.05842269  62.64652874]]
[[ -13.813377   -100.50604558  -31.21571365 -106.73889764  -38.27648437]]
[[ -17.00055049 -102.24619547  -59.20488858  -66.17708149  -24.33553853]]
[[ 3

[[-3.91873379 -8.48864582 -9.58527593 18.95232504 12.54526181]]
[[  2.04524818   3.89075658  10.16661509 -14.61453014  -6.67088458]]
[[ 1.85625876  4.57083092 -0.65787913 -4.2059997  -5.81162228]]
[[-3.90150694 -8.4615875  -9.50873596 18.82052984 12.48250686]]
[[  2.02485641   3.85378846  10.06577523 -14.46533089  -6.60316596]]
[[ 1.85969875  4.58112657 -0.63215936 -4.22569387 -5.81759613]]
[[-3.88455516 -8.43491503 -9.43361587 18.69102477 12.4207621 ]]
[[  2.00493799   3.81777143   9.96720056 -14.31931678  -6.5369117 ]]
[[ 1.86293274  4.59084417 -0.60732437 -4.24443352 -5.82308955]]
[[-3.86787073 -8.4086156  -9.35987619 18.56375029 12.36000125]]
[[  1.98547772   3.7826722    9.87082035 -14.1763938   -6.47207803]]
[[ 1.86596851  4.60000482 -0.58334149 -4.26225497 -5.82812087]]
[[-3.85144623 -8.38267702 -9.28747887 18.43864877 12.3001989 ]]
[[  1.966461     3.74845892   9.77656666 -14.03647144  -6.40862281]]
[[ 1.8688135   4.60862877 -0.56017944 -4.27919293 -5.83270764]]
[[-3.8352745  -

[[ 1.24728878  2.52458199  6.15110287 -8.53721494 -3.9294695 ]]
[[ 1.8351197   4.54405702  0.03397518 -4.37993703 -5.61233442]]
[[-3.08240849 -7.06863901 -6.18507806 12.91715197  9.54180392]]
[[ 1.2418242   2.51585213  6.12299763 -8.49375456 -3.91000433]]
[[ 1.83316088  4.53874789  0.03555624 -4.37434125 -5.60575733]]
[[-3.07498508 -7.05460001 -6.15855387 12.86809581  9.51576166]]
[[ 1.23643309  2.50724772  6.09526017 -8.45085507 -3.89079255]]
[[ 1.83118783  4.53339245  0.03705819 -4.36867287 -5.59914769]]
[[-3.06762092 -7.04064017 -6.13231836 12.81952794  9.48994024]]
[[ 1.23111402  2.49876606  6.06788347 -8.4085062  -3.87182949]]
[[ 1.82920112  4.52799239  0.03848349 -4.36293458 -5.59250687]]
[[-3.06031513 -7.02675845 -6.10636696 12.77144077  9.46433636]]
[[ 1.22586558  2.49040453  6.04086067 -8.36669792 -3.85311059]]
[[ 1.82720132  4.52254929  0.03983452 -4.35712896 -5.58583619]]
[[-3.05306689 -7.01295382 -6.08069519 12.72382688  9.43894678]]
[[ 1.2206864   2.48216057  6.01418506 -8

[[ 1.67590707  4.09623064  0.04099384 -3.88255614 -5.09541158]]
[[-2.65271757 -6.19515884 -4.78808744 10.24984973  8.05576783]]
[[ 0.97438593  2.09511243  4.73438912 -6.34783823 -2.9516922 ]]
[[ 1.67376909  4.09004206  0.04048306 -3.87567535 -5.08851719]]
[[-2.64815503 -6.18515449 -4.77487217 10.22351358  8.04020939]]
[[ 0.97198262  2.09132835  4.72179411 -6.32855837 -2.94310671]]
[[ 1.67163477  4.08385993  0.03997085 -3.86880602 -5.08163328]]
[[-2.64361739 -6.17518828 -4.76176496 10.19736439  8.02473999]]
[[ 0.96960028  2.08757546  4.70930707 -6.30945166 -2.93459871]]
[[ 1.66950415  4.07768445  0.03945752 -3.86194847 -5.07476002]]
[[-2.63910442 -6.16525991 -4.74876459 10.17140013  8.00935873]]
[[ 0.9672386   2.08385327  4.69692652 -6.29051579 -2.92616718]]
[[ 1.66737729  4.07151584  0.03894336 -3.855103   -5.06789756]]
[[-2.63461589 -6.15536911 -4.73586987 10.14561879  7.99406474]]
[[ 0.9648973   2.08016132  4.68465098 -6.27174851 -2.91781108]]
[[ 1.66525427  4.06535428  0.03842865 -3

[[-2.36358129 -5.52719789 -4.02438773  8.66792255  7.07688858]]
[[ 0.83592611  1.87150954  4.00602243 -5.25232503 -2.46439499]]
[[ 1.52448049  3.64796216  0.01083259 -3.39921294 -4.60181107]]
[[-2.36040661 -5.5194717  -4.01685502  8.65153797  7.06620605]]
[[ 0.83454116  1.86918378  3.99871394 -5.24160783 -2.45963203]]
[[ 1.52270395  3.64258527  0.01065837 -3.39363475 -4.59593694]]
[[-2.35724511 -5.51176905 -4.00937231  8.63524258  7.05556898]]
[[ 0.83316442  1.86686936  3.9914485  -5.2309608  -2.45490031]]
[[ 1.52093229  3.63722046  0.01049064 -3.3880748  -4.59007668]]
[[-2.35409671 -5.50408982 -4.00193914  8.6190356   7.04497699]]
[[ 0.83179581  1.86456616  3.98422566 -5.2203832  -2.45019948]]
[[ 1.51916549  3.63186773  0.0103294  -3.38253306 -4.58423026]]
[[-2.3509613  -5.4964339  -3.99455506  8.60291626  7.03442975]]
[[ 0.83043525  1.86227407  3.97704497 -5.20987431 -2.44552923]]
[[ 1.51740355  3.62652707  0.01017464 -3.3770095  -4.57839767]]
[[-2.3478388  -5.48880114 -3.98721961  8

[[ 0.74922894  1.7202989   3.54808033 -4.59629673 -2.17286041]]
[[ 1.40249884  3.27272992  0.01473363 -3.02395461 -4.19296554]]
[[-2.15172779 -4.99302883 -3.56281397  7.62025134  6.36582595]]
[[ 0.74828575  1.71858205  3.54309578 -4.58934735 -2.16977146]]
[[ 1.40105629  3.26822241  0.01498885 -3.0196199  -4.18806199]]
[[-2.14934204 -4.98680447 -3.55808462  7.60896724  6.35783345]]
[[ 0.74734658  1.71687082  3.53813249 -4.58243203 -2.16669761]]
[[ 1.39961758  3.26372537  0.01524849 -3.01529927 -4.18316988]]
[[-2.14696416 -4.98059619 -3.55338098  7.5977313   6.34986749]]
[[ 0.7464114   1.71516515  3.5331903  -4.57555048 -2.16363873]]
[[ 1.39818268  3.25923876  0.01551253 -3.01099267 -4.17828918]]
[[-2.14459408 -4.97440391 -3.54870283  7.58654315  6.34192791]]
[[ 0.74548018  1.71346501  3.52826904 -4.56870242 -2.16059469]]
[[ 1.3967516   3.25476255  0.01578092 -3.00670003 -4.17341985]]
[[-2.14223177 -4.96822756 -3.54404996  7.57540245  6.33401455]]
[[ 0.74455288  1.71177036  3.52336852 -4

[[ 1.3004269   2.9503372   0.04541296 -2.72371321 -3.84220386]]
[[-1.98609911 -4.55091636 -3.25773034  6.86202224  5.81136041]]
[[ 0.68496619  1.59920181  3.20859037 -4.13334126 -1.96694487]]
[[ 1.29924212  2.94655865  0.04591622 -2.72030603 -3.83808998]]
[[-1.98420831 -4.54576046 -3.25450659  6.85364729  5.80503484]]
[[ 0.68426244  1.59782783  3.20487544 -4.12839209 -1.96474141]]
[[ 1.29806015  2.94278835  0.04642152 -2.7169087  -3.83398496]]
[[-1.98232258 -4.54061618 -3.25129695  6.84530079  5.79872637]]
[[ 0.68356094  1.59645721  3.20117251 -4.1234614  -1.96254612]]
[[ 1.29688097  2.93902627  0.04692882 -2.71352118 -3.82988878]]
[[-1.98044191 -4.53548347 -3.24810133  6.83698259  5.7924349 ]]
[[ 0.68286169  1.59508992  3.19748152 -4.11854907 -1.96035894]]
[[ 1.29570458  2.93527239  0.04743812 -2.71014342 -3.8258014 ]]
[[-1.97856627 -4.53036231 -3.24491963  6.82869249  5.78616034]]
[[ 0.68216466  1.59372595  3.19380238 -4.11365496 -1.95817981]]
[[ 1.29453097  2.93152669  0.04794937 -2

In [93]:
def predict(W,PHI):
    Y_predict = np.zeros((PHI.shape[0],1))
    chance = np.zeros((50,3))
    for inx in range(1,4):
        for order in range(50):
            chance[order,inx-1] = get_P(W,PHI,inx,order)
    for i in range(PHI.shape[0]):
        Y_predict[[i],0] = np.argmax(chance[[i],:], axis = 1) + 1
    print(chance)
    return Y_predict

Y_predict = predict(W,PHI_test)
print(Y_predict)

[[5.01313019e-02 6.07864806e-01 3.42003892e-01]
 [7.51449830e-03 4.36434428e-01 5.56051073e-01]
 [9.46369571e-01 5.06408276e-02 2.98960180e-03]
 [9.57250079e-01 4.03060197e-02 2.44390152e-03]
 [9.57633585e-01 4.01223655e-02 2.24404969e-03]
 [5.80725311e-02 5.76008772e-01 3.65918697e-01]
 [1.38507968e-02 4.82645079e-01 5.03504124e-01]
 [9.11284285e-01 8.18524359e-02 6.86327943e-03]
 [9.75408698e-01 2.34365203e-02 1.15478138e-03]
 [3.90799865e-03 4.48451662e-01 5.47640339e-01]
 [2.18179832e-02 5.38871919e-01 4.39310098e-01]
 [4.39263972e-03 3.41673951e-01 6.53933409e-01]
 [8.83903439e-01 1.06896089e-01 9.20047147e-03]
 [6.87421108e-02 6.16604048e-01 3.14653841e-01]
 [3.28844597e-03 4.07023467e-01 5.89688087e-01]
 [3.89773337e-02 5.72403898e-01 3.88618768e-01]
 [9.60810224e-01 3.73939606e-02 1.79581509e-03]
 [9.31589753e-01 6.33976489e-02 5.01259835e-03]
 [5.56996159e-02 5.55253506e-01 3.89046878e-01]
 [9.75982590e-01 2.28049700e-02 1.21244010e-03]
 [5.48416431e-03 3.81972464e-01 6.125433

In [66]:
LR = LogisticRegression()
LR.fit(PHI_train,Y_train)
predict_results=LR.predict(PHI_test)
print(predict_results)
from sklearn.metrics import accuracy_score
print(accuracy_score(predict_results, Y_test))

[2. 3. 1. 1. 1. 2. 2. 1. 1. 3. 2. 3. 1. 2. 3. 2. 1. 1. 2. 1. 3. 2. 3. 3.
 1. 3. 3. 3. 3. 3. 2. 3. 2. 1. 3. 2. 1. 2. 3. 1. 1. 1. 1. 2. 1. 2. 2. 2.
 3. 3.]
0.92


/Users/huangyuang/opt/anaconda3/lib/python3.9/site-packages/sklearn/utils/validation.py:63: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  return f(*args, **kwargs)
/Users/huangyuang/opt/anaconda3/lib/python3.9/site-packages/sklearn/linear_model/_logistic.py:763: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


In [94]:
print(accuracy_score(Y_predict, Y_test))

0.98
